languageCode = "en-us"
title = "zhoumingjun's blog"
baseURL = "https://zhoumingjun.github.io"
theme = "hugo-bootstrap-premium"
disqusShortname = "zhoumingjun"

[permalinks]
    post = "/:year/:month/:day/:slug/"

[taxonomies]
    tag = "tags"
    topic = "topics"
    category = "categories"

[author]
    name = "zhoumingjun"
    email = "zhoumingjun@gmail.com"

[params]
    # You can use markdown here.
    BrandImage = "" #top header brand image.
    brand = "zhoumingjun's blog" # brand image alt text.
    topline = "this is the personal blog"
    footline = "code with <i class='fa fa-heart'></i>"

    # Show a sidebar menu
    showRightSidebar = true

    # Text for the top menu link, which goes the root URL for the site.
    # Default (if omitted) is "Home".
    home = "home"

    mailmunchid = "" # Mailmunch site id
    sumomeid = "" # Sumome id

    # Select a syntax highight.
    # Check the static/css/highlight directory for options.
    highlight = "default"

    # Google Analytics.
    googleAnalytics = "Your Google Analytics tracking code"

    # Sidebar social links.
    github = "enten/hugo-boilerplate" # Your Github profile ID
    bitbucket = "" # Your Bitbucket profile ID
    linkedin = "" # Your LinkedIn profile ID (from public URL)
    googleplus = "" # Your Google+ profile ID
    facebook = "" # Your Facebook profile ID
    twitter = "" # Your Twitter profile ID
    youtube = ""  # Your Youtube channel ID
    flattr = ""  # populate with your flattr uid

[params.theme]
  name = "united"

[blackfriday]
    angledQuotes = true
    fractions = false
    hrefTargetBlank = false
    latexDashes = true
    plainIdAnchors = true
    extensions = []
    extensionmask = []

[[menu.main]]
name = "home"
pre = ""
weight = 1
identifier = "home"
url = "/"

[[menu.main]]
name = "post"
pre = ""
weight = 2
identifier = "Post"
url = "/post"

[[menu.main]]
name = "about"
pre = ""
weight = 3
identifier = "about"
url = "/about"

 